apiVersion: v1
kind: Secret
metadata:
  name: fabric-credentials
  namespace: greenstand
type: Opaque
stringData:
  FABRIC_CA_ADMIN_USER: admin
  FABRIC_CA_ADMIN_PASSWORD: adminpw
  FABRIC_CA_URL: https://fabric-ca.org1.example.com:7054
  FABRIC_MSP_ID: Org1MSP
  FABRIC_WALLET_PATH: /data/wallet
