version: 1.4.0
port: 7054
debug: true
crlsizelimit: 512000

tls:
  enabled: true
  certfile: /etc/hyperledger/fabric-ca-server/ca-cert.pem
  keyfile: /etc/hyperledger/fabric-ca-server/ca-key.pem

ca:
  name: root-ca
  keyfile: /etc/hyperledger/fabric-ca-server/ca-key.pem
  certfile: /etc/hyperledger/fabric-ca-server/ca-cert.pem
  chainfile: /etc/hyperledger/fabric-ca-server/ca-chain.pem

crl:
  expiry: 24h

registry:
  maxenrollments: -1

db:
  type: sqlite3
  datasource: /etc/hyperledger/fabric-ca-server/fabric-ca-server.db
  tls:
    enabled: false

csr:
  cn: root-ca
  keyrequest:
    algo: ecdsa
    size: 256
  names:
    - C: US
      ST: "North Carolina"
      L: "Durham"
      O: Hyperledger
      OU: Fabric
  hosts:
    - root-ca
    - root-ca.hlf-ca.svc.cluster.local
    - localhost
    - 127.0.0.1
    - 165.22.135.70

bccsp:
  default: SW
  sw:
    hash: SHA2
    security: 256
    filekeystore:
      keystore: msp/keystore
