server:
  ca:
    name: ca.org1.example.com
    keyfile: /etc/hyperledger/fabric-ca-server-config/priv_sk
    certfile: /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem

  cafiles:
    - /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem

  tls:
    enabled: false
    certfile: /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
    keyfile: /etc/hyperledger/fabric-ca-server-config/priv_sk

  port: 7054
  address: 0.0.0.0
  loglevel: debug

  db:
    datasource: fabric-ca-server.db
    type: sqlite3

  registry:
    maxenrollments: -1
    identities:
      - name: admin
        pass: adminpw
        type: client
        affiliation: ""
        maxenrollments: -1
        attrs:
          hf.Registrar.Roles: "*"
          hf.Registrar.Attributes: "*"
          hf.Revoker: true
          hf.IntermediateCA: true
          hf.GenCRL: true
          hf.AffiliationMgr: true
